export enum WeaponRef {
  AssaultGun = 'assault-gun',
  BusterSword = 'buster-sword',
  CannonBall = 'cannon-ball',
  FPtShuriken = '4-pt-shuriken',
  FullMetalStaff = 'full-metal-staff',
  GatlingGun = 'gatling-gun',
  GuardStick = 'guard-stick',
  LeatherGlove = 'leather-glove',
  MetalKnuckle = 'metal-knuckle',
  MythrilClaw = 'mythril-claw',
  MythrilClip = 'mythril-clip',
  MythrilRod = 'mythril-rod',
  MythrilSaber = 'mythril-saber',
}
